config/routes.rb
Rails.application.routes.draw do
  resources :preferences

  resources :uno_classes

  resources :users 
  get '/nextPage' => "users#nextPage"
  get '/prefsPage' => "users#prefsPage"
   get '/renderIndex' => "users#Renderindex"
  root :to => 'users#index'
  get '/changeclasses' =>  "users#changeclasses"
  get '/users/changeclasses' =>  "users#changeclasses"
 

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/users_controller.rb
require 'json'

class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  # GET /users
  # GET /users.json
  def index
    @pageNum = 0
    session[:message] = ""
    session[:activate] = 1
    #@users = User.all
    myList = [["A",1],["B"],2]
    @classList = myList
    render "index.html.erb"
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  def prefsPage
    total = 0
    UnoClass.all.each do |uno_class|
      if uno_class.sessionId.to_s == request.session_options[:id].to_s
      total = total + 1
      end
    end
    if total == 0
      session[:message] = "You must enter at least one class"
      render "index.html.erb"
    else
      session[:message]  = ""
      render "prefsPage"
    end
  #render "prefsPage"
  end

  def pPage
    puts "HERE IS WORKING"
    render "pPage.html.erb"
  end

  def nextPage
    session[:page_num] = params[:myAction].to_i
    if(session[:page_num]== nil)
      session[:page_num]= 1
    end
    if(params[:myAction].to_i < 1)
      session[:page_num] = 1
    end
    @pageNum = session[:page_num]
    if(session[:calendars] == nil)
      session[:calendars] = getCalendars()
    end
    session[:calendars] = getCalendars()
    @calendars = session[:calendars]
    puts "Calendars"
    p @calendars
    if(@pageNum > @calendars.length)
      @pageNum = @calendars.length
    end
    if(@calendars.length == 0)
      session[:message] = "No class combinations could be found"
      render "index.html.erb"
    else
      session[:message] = ""
      setCalendarVars(@calendars, @pageNum)

      render "nextPage"
    end
  end

  def setCalendarVars(cals, page)
    page = page - 1
    resetVars()
    currentClass = 0
    cals[page].each do |c|
      startDate = ""
      endDate = ""
      if(c[1] != "TBA")
        c[1] = addTimeIfNecessary(c[1])
        c[2] = addTimeIfNecessary(c[2])
      startDate = c[3]
      endDate = c[3]
      allDay = false
      else
        c[1] = "12:00"
        c[2] = "12:00"
        startDate = "2001-1-1"
        endDate = "2099-1-1"
        allDay = true
        c[4] = c[4] + " - Online"
      end
      if(currentClass == 0)
        @title1 = c[0] + " " + c[4]
        @start1 = startDate + " " + c[1] + ":00"
        @end1 = endDate + " " + c[2] + ":00"
        @allDay1 = allDay
      elsif currentClass == 1
        @title2 = c[0] + " " + c[4]
        @start2 = startDate + " " + c[1] + ":00"
        @end2 = endDate + " " + c[2] + ":00"
        @allDay2 = allDay
      elsif currentClass == 2
        @title3 = c[0] + " " + c[4]
        @start3 = startDate + " " + c[1] + ":00"
        @end3 = endDate + " " + c[2] + ":00"
        @allDay3 = allDay
      elsif currentClass == 3
        @title4 = c[0] + " " + c[4]
        @start4 = startDate + " " + c[1] + ":00"
        @end4 = endDate + " " + c[2] + ":00"
        @allDay4 = allDay
      elsif currentClass == 4
        @title5 = c[0] + " " + c[4]
        @start5 = startDate + " " + c[1] + ":00"
        @end5 = endDate + " " + c[2] + ":00"
        @allDay5 = allDay
      elsif currentClass == 5
        @title6 = c[0] + " " + c[4]
        @start6 = startDate + " " + c[1] + ":00"
        @end6 = endDate + " " + c[2] + ":00"
        @allDay6 = allDay
      elsif currentClass == 6
        @title7 = c[0]  + " " + c[4]
        @start7 = startDate + " " + c[1] + ":00"
        @end7 = endDate + " " + c[2] + ":00"
        @allDay7 = allDay
      elsif currentClass == 7
        @title8 = c[0] + " " + c[4]
        @start8 = startDate + " " + c[1] + ":00"
        @end8 = endDate + " " + c[2] + ":00"
        @allDay8 = allDay
      elsif currentClass == 8
        @title9 = c[0] + " " + c[4]
        @start9 = startDate + " " + c[1] + ":00"
        @end9 = endDate + " " + c[2] + ":00"
        @allDay9 = allDay
      elsif currentClass == 9
        @title10 = c[0] + " " + c[4]
        @start10 = startDate + " " + c[1] + ":00"
        @end10 = endDate + " " + c[2] + ":00"
        @allDay10 = allDay
      end
      currentClass = currentClass + 1
    end
  end

  def addTimeIfNecessary(time)
    timedata = time.match(/(\d+):(\d+)/)
    timedata.captures
    hour = timedata[1].to_i
    minuite = timedata[2].to_i
    if hour < 8
    hour = hour + 12
    end
    ret = hour.to_s + ":" + minuite.to_s
    ret
  end

  def resetVars()
    @title1 = nil
    @end1 = nil
    @start1 = nil
    @title2 = nil
    @end2 = nil
    @start2 = nil
    @title3 = nil
    @end3 = nil
    @start3 = nil
    @title4 = nil
    @end4 = nil
    @start4 = nil
    @title5 = nil
    @end5 = nil
    @start5 = nil
    @title6 = nil
    @end6 = nil
    @start6 = nil
    @title7 = nil
    @end7 = nil
    @start7 = nil
    @title8 = nil
    @end8 = nil
    @start8 = nil
    @title9 = nil
    @end9 = nil
    @start9 = nil
    @title10 = nil
    @end10 = nil
    @start10 = nil
  end

  def getCalendars()
    classes = getAllClasses()
    calendadrs = Array.new
    allClasses = splitClasses(classes)
    allCalendars = Array.new
    theseCals = getCalendarsRecursive(allClasses, Array.new, allCalendars)
    filterCals = filterCalendars(theseCals)
    p filterCals
    filterCals
  #printArrayRec(allCalendars, 0)
  end

  def filterCalendars(theseCals)
    list = Array.new
    prefs = Array.new
    Preference.all.each do |c|
      if c.sessionid.to_s == request.session_options[:id].to_s
        pr = Array.new
        pr.push(c.kind)
        pr.push(c.startTime.strftime("%H:%M"))
        if(c.kind == 3)
          pr.push(c.endTime.strftime("%H:%M"))
        end
        pr.push(getDate(c.day))
      prefs.push(pr)
      end
    end
    valid = true
    theseCals.each do |c|
      toAdd = Array.new
      c.each do |cl|
        thisValid = isValid(cl, prefs)
        if thisValid == false
        break
        else
        prefs.push(thisValid)
        toAdd.push(cl)
        end
      end
      if(!toAdd.empty?)
      list.push(toAdd)
      end
    end
    list
  end

  def isValid(c, prefs)
    valid = true
    prefs.each do |pref|
      if pref.fetch(0) == 1
        if(pref.fetch(2)  == c.fetch(3))
          t1 = Time.parse(pref.fetch(1))
          t2 = Time.parse(c.fetch(1))
          if t2 < t1
          valid = false
          break
          end
        end
      end
      if pref.fetch(0) == 2
        if(pref.fetch(2)  == c.fetch(3))
          t1 = Time.parse(pref.fetch(1))
          t2 = Time.parse(c.fetch(2))
          if t2 > t1
          valid = false
          break
          end
        end
      end
      if pref.fetch(0) == 3
        if(pref.fetch(3)  == c.fetch(3))
          prefT1 = Time.parse(pref.fetch(1))
          prefT2 = Time.parse(pref.fetch(2))
          cT1 = Time.parse(c.fetch(2))
          cT2 = Time.parse(c.fetch(2))
          if (cT1 > prefT1 && cT1 < prefT2) || (cT2 > prefT1 && cT2 < prefT2)
          valid = false
          break
          end
          if(cT1 < prefT1 && cT2 > prefT2)
          valid = false
          break
          end
        end
      end
    end
    if(valid)
      puts "Valid"
      pref = Array.new
    pref.push(3)
    pref.push(c.fetch(1))
    pref.push(c.fetch(2))
    pref.push(c.fetch(3))
    return pref
    else
      puts "Not Valid"
    end
    valid
  end

  def getDate(day)
    ret = ""
    if(day == "M")
      ret = "2001-01-01"
    elsif (day == "T")
      ret = "2001-01-02"
    elsif (day == "W")
      ret = "2001-01-03"
    elsif (day == "R")
      ret = "2001-01-04"
    elsif (day == "F")
      ret = "2001-01-05"
    elsif (day == "Sa")
      ret = "2001-01-06"
    elsif (day == "Su")
      ret = "2001-01-07"
    end
    ret
  end

  def getCalendarsRecursive(classes, currentCalendar, allCalendars)
    # puts "All calendars"
    # p allCalendars
    if classes.length == 0
    return allCalendars
    end
    classes[0].each do |section|
      sectionLength = section.length
      section.each do |c|
        currentCalendar.push(c)
      end
      if(classes.length == 1)
        #@allTheseCalendars = allCalendars
        copy = Array.new(currentCalendar)
      allCalendars.push(copy)
      else
        newArray = getCalendarsRecursive(classes[1..-1], currentCalendar, allCalendars)
      end
      for i in 1..sectionLength
        currentCalendar.pop
      end
    end
    return allCalendars
  end

  def splitClasses(classes)
    allClasses = Array.new
    classes.each do |myClass|
      classGroup = Array.new
      myClass.each do |c|
        newDate = Date.strptime('2001-01-01', '%Y-%m-%d')
        individualClassGroup = Array.new
        for i in 1..5
          if(newDate.wday == 1)
            if c[3].include? "M"
              thisClass = Array.new
            thisClass.push(c[0])
            thisClass.push(c[1])
            thisClass.push(c[2])
            thisClass.push(newDate.to_s)
            thisClass.push(c[4])
            individualClassGroup.push(thisClass)
            end
          end
          if(newDate.wday == 2)
            if c[3].include? "T"
              thisClass = Array.new
            thisClass.push(c[0])
            thisClass.push(c[1])
            thisClass.push(c[2])
            thisClass.push(newDate.to_s)
            thisClass.push(c[4])
            individualClassGroup.push(thisClass)
            end
          end
          if(newDate.wday == 3)
            if c[3].include? "W"
              thisClass = Array.new
            thisClass.push(c[0])
            thisClass.push(c[1])
            thisClass.push(c[2])
            thisClass.push(newDate.to_s)
            thisClass.push(c[4])
            individualClassGroup.push(thisClass)
            end
          end
          if(newDate.wday == 4)
            if c[3].include? "R"
              thisClass = Array.new
            thisClass.push(c[0])
            thisClass.push(c[1])
            thisClass.push(c[2])
            thisClass.push(newDate.to_s)
            thisClass.push(c[4])
            individualClassGroup.push(thisClass)
            end
          end

app/helpers/users_helper.rb
require 'rubygems'
require 'nokogiri'
require 'open-uri'

module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/changeclasses.html.erb
<%= link_to "RenderIndex", :controller => :users, :action => :Renderindex %> 

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/nextPage.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>SoftwareEngineeringApp</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
		<div id="title1" data-lat="<%= @title1 %>"></div>
		<div id="end1" data-lat="<%= @end1 %>"></div>
		<div id="start1" data-lat="<%= @start1 %>"></div>
		<div id="all1" data-lat="<%= @allDay1 %>"></div>
		<div id="title2" data-lat="<%= @title2 %>"></div>
		<div id="end2" data-lat="<%= @end2 %>"></div>
		<div id="start2" data-lat="<%= @start2 %>"></div>
		<div id="all2" data-lat="<%= @allDay2 %>"></div>
		<div id="title3" data-lat="<%= @title3 %>"></div>
		<div id="end3" data-lat="<%= @end3 %>"></div>
		<div id="start3" data-lat="<%= @start3 %>"></div>
		<div id="all3" data-lat="<%= @allDay3 %>"></div>
		<div id="title4" data-lat="<%= @title4 %>"></div>
		<div id="end4" data-lat="<%= @end4 %>"></div>
		<div id="start4" data-lat="<%= @start4 %>"></div>
		<div id="all4" data-lat="<%= @allDay4 %>"></div>
		<div id="title5" data-lat="<%= @title5 %>"></div>
		<div id="end5" data-lat="<%= @end5 %>"></div>
		<div id="start5" data-lat="<%= @start5 %>"></div>
		<div id="all5" data-lat="<%= @allDay5 %>"></div>
		<div id="title6" data-lat="<%= @title6 %>"></div>
		<div id="end6" data-lat="<%= @end6 %>"></div>
		<div id="start6" data-lat="<%= @start6 %>"></div>
		<div id="all6" data-lat="<%= @allDay6 %>"></div>
		<div id="title7" data-lat="<%= @title7 %>"></div>
		<div id="end7" data-lat="<%= @end7 %>"></div>
		<div id="start7" data-lat="<%= @start7 %>"></div>
		<div id="all7" data-lat="<%= @allDay7 %>"></div>
		<div id="title8" data-lat="<%= @title8 %>"></div>
		<div id="end8" data-lat="<%= @end8 %>"></div>
		<div id="start8" data-lat="<%= @start8 %>"></div>
		<div id="all8" data-lat="<%= @allDay8 %>"></div>
		<div id="title9" data-lat="<%= @title9 %>"></div>
		<div id="end9" data-lat="<%= @end9 %>"></div>
		<div id="start9" data-lat="<%= @start9 %>"></div>
		<div id="all9" data-lat="<%= @allDay9 %>"></div>
		<div id="title10" data-lat="<%= @title10 %>"></div>
		<div id="end10" data-lat="<%= @end10 %>"></div>
		<div id="start10" data-lat="<%= @start10 %>"></div>
		<div id="all10" data-lat="<%= @allDay10 %>"></div>

		<script>
		var title1 = $("#title1").data("lat");
		var end1 = $("#end1").data("lat");
		var start1 = $("#start1").data("lat");
		var all1 = $("#all1").data("lat");
		var title2 = $("#title2").data("lat");
		var end2 = $("#end2").data("lat");
		var start2 = $("#start2").data("lat");
		var all2 = $("#all2").data("lat");
		var title3 = $("#title3").data("lat");
		var end3 = $("#end3").data("lat");
		var start3 = $("#start3").data("lat");
		var all3 = $("#all3").data("lat");
		var title4 = $("#title4").data("lat");
		var end4 = $("#end4").data("lat");
		var start4 = $("#start4").data("lat");
		var all4 = $("#all4").data("lat");
		var title5 = $("#title5").data("lat");
		var end5 = $("#end5").data("lat");
		var start5 = $("#start5").data("lat");
		var all5 = $("#all5").data("lat");
		var title6 = $("#title6").data("lat");
		var end6 = $("#end6").data("lat");
		var start6 = $("#start6").data("lat");
		var all6 = $("#all6").data("lat");
		var title7 = $("#title7").data("lat");
		var end7 = $("#end7").data("lat");
		var start7 = $("#start7").data("lat");
		var all7 = $("#all7").data("lat");
		var title8 = $("#title8").data("lat");
		var end8 = $("#end8").data("lat");
		var start8 = $("#start8").data("lat");
		var all8 = $("#all8").data("lat");
		var title9 = $("#title9").data("lat");
		var end9 = $("#end9").data("lat");
		var start9 = $("#start9").data("lat");
		var all9 = $("#all9").data("lat");
		var title10 = $("#title10").data("lat");
		var end10 = $("#end10").data("lat");
		var start10 = $("#start10").data("lat");
		var all10 = $("#all10").data("lat");
			$(document).ready(function() {

				// page is now ready, initialize the calendar...

				$('#calendar').fullCalendar({
					defaultView : 'agendaWeek',
					//contentHeight: "auto",
					height : 600,
					weekends : false,
					year: 2001,
 					month: 0,
 					date: 1,
					header: {
        				left: '',
        				center: 'title',
        				right: ''
    				},
					events : [{title:title1,end: end1,start: start1, allDay: all1},
							  {title:title2,end: end2,start: start2, allDay: all2},
							  {title:title3,end: end3,start: start3, allDay: all3},
							  {title:title4,end: end4,start: start4, allDay: all4},
							  {title:title5,end: end5,start: start5, allDay: all5},
							  {title:title6,end: end6,start: start6, allDay: all6},
							  {title:title7,end: end7,start: start7, allDay: all7},
							  {title:title8,end: end8,start: start8, allDay: all8},
							  {title:title9,end: end9,start: start9, allDay: all9},
							  {title:title10,end: end10,start: start10, allDay: all10}
					]

				});
				$('#calendar').fullCalendar('gotoDate', '2014-09-12');

			});
		</script>
	</head>


</html>

	<header>
	<%= image_tag 'UNO_Logo1.jpg', size: '150x150' %>
	<p>UNO ClassCaddy</p>
	</header>
	
	<section class="information" id="main">
		<section class="information" id="welcome">
		<table id="calHeading">
		<tr>
			<td><h4><%= link_to "<<Previous Schedule", :controller => :users, :action => :nextPage, :myAction => (@pageNum -1)%></h4></td>
			<td><h2>Schedule <%=@pageNum%></h2></td>
			<td><h4><%= link_to "Next Schedule>>", :controller => :users, :action => :nextPage, :myAction => (@pageNum +1)%></h4></td>
		</tr>
		</table>
		</section>
	<body>
		<div id='calendar'></div>
		
		<table id="calButtons">
		<tr>
			<td><a href="uno_classes"><input type="button" value="Edit Classes" /></a></td>
		</tr>
		<tr class="spacer"><td>/////////////////////////</td></tr>
		<tr>
			<td><a href="prefsPage"><input type="button" value="Edit Preferences" /></a></td>
		</tr>
		</table>

		<a href="" style="margin-left: 42%;">View Printer-Friendly Version</a>
	</body>
	</section>

	<!-- Creation information is included in this footer.-->
	<footer style="margin-top: 5%;">Created by Erik Dodge, Joseph Eley, Christian Ressler, Jason Lynn and Ibrahim Nikiema</footer>

app/views/users/pPage.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>SoftwareEngineeringApp</title>
		<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
		<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
		<%= csrf_meta_tags %>
		<div id="title1" data-lat="<%= @title1 %>"></div>
		<div id="end1" data-lat="<%= @end1 %>"></div>
		<div id="start1" data-lat="<%= @start1 %>"></div>
		<div id="all1" data-lat="<%= @allDay1 %>"></div>
		<div id="title2" data-lat="<%= @title2 %>"></div>
		<div id="end2" data-lat="<%= @end2 %>"></div>
		<div id="start2" data-lat="<%= @start2 %>"></div>
		<div id="all2" data-lat="<%= @allDay2 %>"></div>
		<div id="title3" data-lat="<%= @title3 %>"></div>
		<div id="end3" data-lat="<%= @end3 %>"></div>
		<div id="start3" data-lat="<%= @start3 %>"></div>
		<div id="all3" data-lat="<%= @allDay3 %>"></div>
		<div id="title4" data-lat="<%= @title4 %>"></div>
		<div id="end4" data-lat="<%= @end4 %>"></div>
		<div id="start4" data-lat="<%= @start4 %>"></div>
		<div id="all4" data-lat="<%= @allDay4 %>"></div>
		<div id="title5" data-lat="<%= @title5 %>"></div>
		<div id="end5" data-lat="<%= @end5 %>"></div>
		<div id="start5" data-lat="<%= @start5 %>"></div>
		<div id="all5" data-lat="<%= @allDay5 %>"></div>
		<div id="title6" data-lat="<%= @title6 %>"></div>
		<div id="end6" data-lat="<%= @end6 %>"></div>
		<div id="start6" data-lat="<%= @start6 %>"></div>
		<div id="all6" data-lat="<%= @allDay6 %>"></div>
		<div id="title7" data-lat="<%= @title7 %>"></div>
		<div id="end7" data-lat="<%= @end7 %>"></div>
		<div id="start7" data-lat="<%= @start7 %>"></div>
		<div id="all7" data-lat="<%= @allDay7 %>"></div>
		<div id="title8" data-lat="<%= @title8 %>"></div>
		<div id="end8" data-lat="<%= @end8 %>"></div>
		<div id="start8" data-lat="<%= @start8 %>"></div>
		<div id="all8" data-lat="<%= @allDay8 %>"></div>
		<div id="title9" data-lat="<%= @title9 %>"></div>
		<div id="end9" data-lat="<%= @end9 %>"></div>
		<div id="start9" data-lat="<%= @start9 %>"></div>
		<div id="all9" data-lat="<%= @allDay9 %>"></div>
		<div id="title10" data-lat="<%= @title10 %>"></div>
		<div id="end10" data-lat="<%= @end10 %>"></div>
		<div id="start10" data-lat="<%= @start10 %>"></div>
		<div id="all10" data-lat="<%= @allDay10 %>"></div>

		<script>
		var title1 = $("#title1").data("lat");
		var end1 = $("#end1").data("lat");
		var start1 = $("#start1").data("lat");
		var all1 = $("#all1").data("lat");
		var title2 = $("#title2").data("lat");
		var end2 = $("#end2").data("lat");
		var start2 = $("#start2").data("lat");
		var all2 = $("#all2").data("lat");
		var title3 = $("#title3").data("lat");
		var end3 = $("#end3").data("lat");
		var start3 = $("#start3").data("lat");
		var all3 = $("#all3").data("lat");
		var title4 = $("#title4").data("lat");
		var end4 = $("#end4").data("lat");
		var start4 = $("#start4").data("lat");
		var all4 = $("#all4").data("lat");
		var title5 = $("#title5").data("lat");
		var end5 = $("#end5").data("lat");
		var start5 = $("#start5").data("lat");
		var all5 = $("#all5").data("lat");
		var title6 = $("#title6").data("lat");
		var end6 = $("#end6").data("lat");
		var start6 = $("#start6").data("lat");
		var all6 = $("#all6").data("lat");
		var title7 = $("#title7").data("lat");
		var end7 = $("#end7").data("lat");
		var start7 = $("#start7").data("lat");
		var all7 = $("#all7").data("lat");
		var title8 = $("#title8").data("lat");
		var end8 = $("#end8").data("lat");
		var start8 = $("#start8").data("lat");
		var all8 = $("#all8").data("lat");
		var title9 = $("#title9").data("lat");
		var end9 = $("#end9").data("lat");
		var start9 = $("#start9").data("lat");
		var all9 = $("#all9").data("lat");
		var title10 = $("#title10").data("lat");
		var end10 = $("#end10").data("lat");
		var start10 = $("#start10").data("lat");
		var all10 = $("#all10").data("lat");
			$(document).ready(function() {

				// page is now ready, initialize the calendar...

				$('#calendar').fullCalendar({
					defaultView : 'agendaWeek',
					//contentHeight: "auto",
					height : 600,
					weekends : false,
					year: 2001,
 					month: 0,
 					date: 1,
					header: {
        				left: '',
        				center: 'title',
        				right: ''
    				},
					events : [{title:title1,end: end1,start: start1, allDay: all1},
							  {title:title2,end: end2,start: start2, allDay: all2},
							  {title:title3,end: end3,start: start3, allDay: all3},
							  {title:title4,end: end4,start: start4, allDay: all4},
							  {title:title5,end: end5,start: start5, allDay: all5},
							  {title:title6,end: end6,start: start6, allDay: all6},
							  {title:title7,end: end7,start: start7, allDay: all7},
							  {title:title8,end: end8,start: start8, allDay: all8},
							  {title:title9,end: end9,start: start9, allDay: all9},
							  {title:title10,end: end10,start: start10, allDay: all10}
					]

				});
				$('#calendar').fullCalendar('gotoDate', '2014-09-12');

			});
		</script>
	</head>


</html>

	
	<body>
		<div id='calendar'></div>
	</body>
	</section>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>