config/routes.rb
Rails.application.routes.draw do
  resources :preferences

  resources :uno_classes

  resources :users 
  get '/nextPage' => "users#nextPage"
  get '/prefsPage' => "users#prefsPage"
   get '/renderIndex' => "users#Renderindex"
  root :to => 'users#index'
  get '/changeclasses' =>  "users#changeclasses"
  get '/users/changeclasses' =>  "users#changeclasses"
 

end

app/models/preference.rb
class Preference < ActiveRecord::Base
end

app/controllers/preferences_controller.rb
class PreferencesController < ApplicationController
  before_action :set_preference, only: [:show, :edit, :update, :destroy]

  # GET /preferences
  # GET /preferences.json
  def index
    @preferences = Preference.all
    render "users/prefsPage.html.erb"
  end

  # GET /preferences/1
  # GET /preferences/1.json
  def show
  end

  # GET /preferences/new
  def new
    @preference = Preference.new
  end

  # GET /preferences/1/edit
  def edit
  end

  # POST /preferences
  # POST /preferences.json
  def create
    @preference = Preference.new(preference_params)

    respond_to do |format|
      if @preference.save
        format.html { redirect_to action: :index}
      else
        format.html { render action: "new" }
      end
    end
  end

  # PATCH/PUT /preferences/1
  # PATCH/PUT /preferences/1.json
  def update
    respond_to do |format|
      if @preference.update(preference_params)
        format.html { redirect_to @preference, notice: 'Preference was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @preference.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /preferences/1
  # DELETE /preferences/1.json
  def destroy
    @preference.destroy
    respond_to do |format|
      format.html { redirect_to preferences_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_preference
      @preference = Preference.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def preference_params
      params.require(:preference).permit(:kind, :startTime, :endTime, :sessionid, :day)
    end
end

app/helpers/preferences_helper.rb
module PreferencesHelper
end

app/views/preferences/_form.html.erb
<%= form_for(@preference) do |f| %>
  <% if @preference.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@preference.errors.count, "error") %> prohibited this preference from being saved:</h2>

      <ul>
      <% @preference.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :kind %><br>
    <%= f.number_field :kind %>
  </div>
  <div class="field">
    <%= f.label :startTime %><br>
    <%= f.time_select :startTime %>
  </div>
  <div class="field">
    <%= f.label :endTime %><br>
    <%= f.time_select :endTime %>
  </div>
  <div class="field">
    <%= f.label :sessionid %><br>
    <%= f.text_field :sessionid %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/preferences/edit.html.erb
<h1>Editing preference</h1>

<%= render 'form' %>

<%= link_to 'Show', @preference %> |
<%= link_to 'Back', preferences_path %>

app/views/preferences/index.html.erb
<h1>Listing preferences</h1>

<table>
  <thead>
    <tr>
      <th>Kind</th>
      <th>Starttime</th>
      <th>Endtime</th>
      <th>Sessionid</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @preferences.each do |preference| %>
      <tr>
        <td><%= preference.kind %></td>
        <td><%= preference.startTime %></td>
        <td><%= preference.endTime %></td>
        <td><%= preference.sessionid %></td>
        <td><%= link_to 'Show', preference %></td>
        <td><%= link_to 'Edit', edit_preference_path(preference) %></td>
        <td><%= link_to 'Destroy', preference, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Preference', new_preference_path %>

app/views/preferences/new.html.erb
<h1>New preference</h1>

<%= render 'form' %>

<%= link_to 'Back', preferences_path %>

app/views/preferences/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Kind:</strong>
  <%= @preference.kind %>
</p>

<p>
  <strong>Starttime:</strong>
  <%= @preference.startTime %>
</p>

<p>
  <strong>Endtime:</strong>
  <%= @preference.endTime %>
</p>

<p>
  <strong>Sessionid:</strong>
  <%= @preference.sessionid %>
</p>

<%= link_to 'Edit', edit_preference_path(@preference) %> |
<%= link_to 'Back', preferences_path %>