config/routes.rb
Rails.application.routes.draw do
  resources :preferences

  resources :uno_classes

  resources :users 
  get '/nextPage' => "users#nextPage"
  get '/prefsPage' => "users#prefsPage"
   get '/renderIndex' => "users#Renderindex"
  root :to => 'users#index'
  get '/changeclasses' =>  "users#changeclasses"
  get '/users/changeclasses' =>  "users#changeclasses"
 

end

app/controllers/uno_classes_controller.rb
class UnoClassesController < ApplicationController
  before_action :set_uno_class, only: [:show, :edit, :update, :destroy]
  # GET /uno_classes
  # GET /uno_classes.json
  def index
    @uno_classes = UnoClass.all
    
    #puts "This is a test"
    render "users/index.html.erb" 
  end

  # GET /uno_classes/1
  # GET /uno_classes/1.json
  def show
  end

  # GET /uno_classes/new
  def new
    @uno_class = UnoClass.new
  end

  # GET /uno_classes/1/edit
  def edit
  end

  # POST /uno_classes
  # POST /uno_classes.json
  def create
    @uno_class = UnoClass.new(uno_class_params)

    respond_to do |format|
      if validClass(@uno_class)
        if @uno_class.save
          session[:message] = ""
          format.html { redirect_to action: :index}
        else
          format.html { render action: "new" }
        end
      else
        session[:message] = "Class did not exist"
        format.html { redirect_to action: :index}
      end
    end
  end

  def validClass(unoClass)
    termNum = 1151
    classDep = unoClass.department
    classNumber = unoClass.course
    url = "http://www.unomaha.edu/class-search/?term="+ termNum.to_s + "&session=&subject=" + classDep.to_s + "&catalog_nbr=" + classNumber.to_s + "&career=&instructor=&class_start_time=&class_end_time=&location=&special=&instruction_mode="
    doc = Nokogiri::HTML(open(url))
    found = false
    doc.search('//table/tr/td/table/tr').each do |tr|
      found = true
    end
    return found
  end

  # PATCH/PUT /uno_classes/1
  # PATCH/PUT /uno_classes/1.json
  def update
    respond_to do |format|
      if @uno_class.update(uno_class_params)
        format.html { redirect_to @uno_class, notice: 'Uno class was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @uno_class.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uno_classes/1
  # DELETE /uno_classes/1.json
  def destroy
    @uno_class.destroy
    respond_to do |format|
      format.html { redirect_to action: :index}
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_uno_class
    @uno_class = UnoClass.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def uno_class_params
    params.require(:uno_class).permit(:department, :course, :section, :startTime, :endTime, :days, :location, :instructor, :sessionId)
  end
end

app/helpers/uno_classes_helper.rb
module UnoClassesHelper
end

app/views/uno_classes/_form.html.erb
<%= form_for(@uno_class) do |f| %>
  <% if @uno_class.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@uno_class.errors.count, "error") %> prohibited this uno_class from being saved:</h2>

      <ul>
      <% @uno_class.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :department %><br>
    <%= f.text_field :department %>
  </div>
  <div class="field">
    <%= f.label :course %><br>
    <%= f.number_field :course %>
  </div>
  <div class="field">
    <%= f.label :section %><br>
    <%= f.number_field :section %>
  </div>
  <div class="field">
    <%= f.label :startTime %><br>
    <%= f.time_select :startTime %>
  </div>
  <div class="field">
    <%= f.label :endTime %><br>
    <%= f.time_select :endTime %>
  </div>
  <div class="field">
    <%= f.label :days %><br>
    <%= f.text_field :days %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :instructor %><br>
    <%= f.text_field :instructor %>
  </div>
  <div class="field">
    <%= f.label :sessionId %><br>
    <%= f.text_field :sessionId %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/uno_classes/edit.html.erb
<h1>Editing uno_class</h1>

<%= render 'form' %>

<%= link_to 'Show', @uno_class %> |
<%= link_to 'Back', uno_classes_path %>

app/views/uno_classes/index.html.erb
<h1>Listing uno_classes</h1>

<table>
  <thead>
    <tr>
      <th>Department</th>
      <th>Course</th>
      <th>Section</th>
      <th>Starttime</th>
      <th>Endtime</th>
      <th>Days</th>
      <th>Location</th>
      <th>Instructor</th>
      <th>Sessionid</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @uno_classes.each do |uno_class| %>
      <tr>
        <td><%= uno_class.department %></td>
        <td><%= uno_class.course %></td>
        <td><%= uno_class.section %></td>
        <td><%= uno_class.startTime %></td>
        <td><%= uno_class.endTime %></td>
        <td><%= uno_class.days %></td>
        <td><%= uno_class.location %></td>
        <td><%= uno_class.instructor %></td>
        <td><%= uno_class.sessionId %></td>
        <td><%= link_to 'Show', uno_class %></td>
        <td><%= link_to 'Edit', edit_uno_class_path(uno_class) %></td>
        <td><%= link_to 'Destroy', uno_class, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Uno class', new_uno_class_path %>

app/views/uno_classes/new.html.erb
<h1>New uno_class</h1>

<%= render 'form' %>

<%= link_to 'Back', uno_classes_path %>

app/views/uno_classes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Department:</strong>
  <%= @uno_class.department %>
</p>

<p>
  <strong>Course:</strong>
  <%= @uno_class.course %>
</p>

<p>
  <strong>Section:</strong>
  <%= @uno_class.section %>
</p>

<p>
  <strong>Starttime:</strong>
  <%= @uno_class.startTime %>
</p>

<p>
  <strong>Endtime:</strong>
  <%= @uno_class.endTime %>
</p>

<p>
  <strong>Days:</strong>
  <%= @uno_class.days %>
</p>

<p>
  <strong>Location:</strong>
  <%= @uno_class.location %>
</p>

<p>
  <strong>Instructor:</strong>
  <%= @uno_class.instructor %>
</p>

<p>
  <strong>Sessionid:</strong>
  <%= @uno_class.sessionId %>
</p>

<%= link_to 'Edit', edit_uno_class_path(@uno_class) %> |
<%= link_to 'Back', uno_classes_path %>